apiVersion: v1
kind: Service
metadata:
  name: platform-service-dify-api
  namespace: acedatacloud
spec:
  type: ClusterIP
  selector:
    app: platform-service-dify-api
  ports:
    - name: http
      port: 5001
      targetPort: 5001
