apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: platform-service-dify-plugin-daemon-storage
  namespace: acedatacloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: cbs-ssd
  volumeMode: Filesystem
  volumeName: platform-service-dify
