apiVersion: v1
kind: Secret
metadata:
  name: platform-service-dify-app
  namespace: acedatacloud
type: Opaque
stringData:
  SECRET_KEY: please-change-me
  INNER_API_KEY_FOR_PLUGIN: please-change-me
  CODE_EXECUTION_API_KEY: please-change-me
  SANDBOX_API_KEY: please-change-me

